from typing import Dict, Any, List
from datetime import datetime, timezone
from ..common.helpers import ensure_dict


def _default_labels(image_url: str) -> List[str]:
    if "food" in image_url.lower():
        return ["food", "restaurant", "tasty"]
    if "temple" in image_url.lower() or "shrine" in image_url.lower():
        return ["culture", "architecture", "landmark"]
    return ["travel", "memory", "placeholder"]


def describe_image(payload: Any) -> Dict[str, Any]:
    data = ensure_dict(payload.data)
    image_url = data.get("image_url", "unknown")
    labels = data.get("labels") or _default_labels(image_url)
    return {
        "dummy": True,
        "image_url": image_url,
        "description": "This is a dummy description generated by the vision service.",
        "labels": labels,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

